development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  encoding: utf8
  min_messages: warning
  timeout: 5000
  url: postgres://kfcsavwghzbvnn:5995dce36a31b630b1f88ed8bae4a02f1aeff284f0dc0548885537bdd878a0be@ec2-54-225-240-168.compute-1.amazonaws.com:5432/de8konnoso18m
  adapter: postgresql
