development: 
  encoding: utf8
  min_messages: warning
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  adapter: postgresql

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  encoding: utf8
  min_messages: warning
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  adapter: postgresql